export { Layout } from "./Layout"
export { Hero } from "./Hero"
export { Services } from "./Services"
export { Testimonials } from "./Testimonials"
export { Contact } from "./Contact"
export { Footer } from "./Footer"
export { Input } from "./Input"
export { Button, Submit } from "./Button"
export { Slider } from "./Slider/Slider"
export { Navigation } from "./Navigation"
export { Header } from "./Header"
export { About } from "./About"
export { Stock } from "./Stock"
